#pragma once
#include "ReflectionHeader.h"

enum class OBJECT_TYPE
{
	CAMERA,
	MESH,
	LIGHT,
	NONE,
};


#ifdef REFLECTION_PROJECT

REFLECT_CHECK_ENUM(OBJECT_TYPE)
BEGIN_REFLECTION_ENUM(OBJECT_TYPE)
ENUM_MEMBER_REFLECTION(CAMERA)
ENUM_MEMBER_REFLECTION(MESH)
ENUM_MEMBER_REFLECTION(LIGHT)
ENUM_MEMBER_REFLECTION(NONE)
END_REFLECTION_ENUM()

#endif // REFLECTION_PROJECT