#include "OBJECT_TYPE.h"

BEGIN_REFLECTION_ENUM(OBJECT_TYPE)
ENUM_MEMBER_REFLECTION(CAMERA)
ENUM_MEMBER_REFLECTION(MESH)
ENUM_MEMBER_REFLECTION(LIGHT)
ENUM_MEMBER_REFLECTION(NONE)
END_REFLECTION_ENUM()